-- Safe intake for physical ingredient stock that was never received in the
-- system. The matching runtime migration is in
-- api/helpers/ingredient_opening_stock.php.

CREATE TABLE IF NOT EXISTS ingredient_opening_stock_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_code VARCHAR(30) NOT NULL UNIQUE,
    ingredient_id INT NOT NULL,
    system_quantity DECIMAL(12,3) NOT NULL,
    counted_quantity DECIMAL(12,3) NOT NULL,
    quantity_to_add DECIMAL(12,3) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    source_type ENUM('opening_balance','unrecorded_delivery') NOT NULL,
    supplier_id INT NULL,
    source_reference VARCHAR(100) NOT NULL,
    supplier_batch_no VARCHAR(50) NULL,
    received_date DATE NOT NULL,
    expiry_date DATE NULL,
    unit_cost DECIMAL(10,2) NULL,
    price_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    price_verified_by INT NULL,
    price_verified_at DATETIME NULL,
    price_reference VARCHAR(100) NULL,
    matched_po_id INT NULL,
    qc_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    qc_verified_by INT NULL,
    qc_verified_at DATETIME NULL,
    qc_notes VARCHAR(500) NULL,
    reason VARCHAR(500) NOT NULL,
    status ENUM('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
    requested_by INT NOT NULL,
    decided_by INT NULL,
    decided_at DATETIME NULL,
    decision_notes VARCHAR(1000) NULL,
    created_batch_id INT NULL,
    request_purpose VARCHAR(30) NOT NULL DEFAULT 'found_stock',
    held_batch_id INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_opening_stock_status (status, created_at),
    INDEX idx_opening_stock_ingredient (ingredient_id, status),
    CONSTRAINT fk_opening_stock_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id),
    CONSTRAINT fk_opening_stock_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_opening_stock_requester FOREIGN KEY (requested_by) REFERENCES users(id),
    CONSTRAINT fk_opening_stock_decider FOREIGN KEY (decided_by) REFERENCES users(id),
    CONSTRAINT fk_opening_stock_batch FOREIGN KEY (created_batch_id) REFERENCES ingredient_batches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
